;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	cua--prefix-copy-handler
	cua-copy-region
	cua-paste
	exit-recursive-edit
	keyboard-escape-quit
	replace-string
	term-interrupt-subjob
	wdired-finish-edit
	))

(setq mc/cmds-to-run-once
      '(
	compose-mail
	cua--prefix-override-handler
	cua-exchange-point-and-mark
	delete-window
	js-eval-defun
	next-buffer
	popup-kill-ring
	previous-buffer
	term
	))
